### ISSUE TITLE
#Add missing tests 

### ISSUE THREAD

**Issue by FedeLochbaum** [PracticaDS/pdes-tp-team_prog#94]
When we started with the project, we left some files that doesn't have a test.

**Comment by LaimeJesus** [comment]
Could you add some examples?

**Comment by LaimeJesus** [comment]
I think we should add integration/e2e tests using cypress(or any other alternative) for the application.
The cases that would be useful to test(automate) are:
* when we create a machine in the grid(select a machine and then click a block on the grid), we should expect that the machine component was created.
* when we move a machine in the grid(select the move action, select a machine to move and then click a block on the grid), we should expect that the machine component was created on the new block and the previous machine component doesn't exists anymore.
* when we delete a machine in the grid(select the delete action and then click a machine on the grid), we should expect that the machine component doesn't exists anymore.
* when we rotate a machine in the grid(select the rotate action, and then click a machine on the grid), we should expect that the machine component's direction was changed.
* there are more cases, like the machines' behaviours, but I think that case would be more harder to test because they depend on the tick which is a asynchronous(non deterministic(?)) operation. We should mock that component or functionality for those tests.

I can start working on adding those integration/e2e tests, what do you think?

**Comment by LaimeJesus** [comment]
We are working this one on ticket #107.
